#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

SKILL_OVERRIDES = {
    "browse": {
        "description": (
            "Browser automation workflow built on the `agent-browser` CLI. Use when "
            "you need to open pages, inspect content, click through flows, fill "
            "forms, capture screenshots, inspect console or network activity, or "
            "compare pages."
        ),
    },
}

GENERATOR_NOTE = (
    "<!-- Generated by tools/convert_gstack.py. Edit the converter, not this file. -->\n\n"
)

UNIVERSAL_RUNTIME_NOTES = (
    "## Runtime Notes\n"
    "- Ask the user directly when the workflow says to stop for input.\n"
    "- Treat `AGENTS.md`, `TODO.md`, and `TODOS.md` as the likely sources of repo-local instructions.\n"
    "- Keep the workflow intent intact, but translate any environment-specific wording to the current toolset.\n\n"
)

BROWSE_SKILL = """# browse

Use `agent-browser` directly for browser automation. Keep commands explicit and prefer the built-in session model instead of adding a second wrapper layer.

## Requirements

- `agent-browser` must be available on `PATH`.
- If browser binaries are missing, run `agent-browser install`.
- Reuse the default session unless isolation matters; close it with `agent-browser close` when the workflow is finished.

## Default Flow

```bash
agent-browser open https://example.com
agent-browser wait --load networkidle
agent-browser snapshot -i
```

Use `snapshot -i` when selectors are unclear, then interact with `@ref` targets from the snapshot output.

## Command Map

```bash
# Open or navigate
agent-browser open https://example.com
agent-browser back
agent-browser forward
agent-browser reload

# Inspect content
agent-browser get title
agent-browser get url
agent-browser get text body
agent-browser get html main
agent-browser snapshot -i

# Interact
agent-browser click @e3
agent-browser fill @e4 "test@example.com"
agent-browser type @e5 "hello"
agent-browser press Enter
agent-browser select @e6 option-a
agent-browser upload @e7 /tmp/file.png
agent-browser wait @e8

# Visual checks
agent-browser screenshot /tmp/page.png
agent-browser screenshot --full /tmp/page-full.png
agent-browser pdf /tmp/page.pdf

# Debugging
agent-browser console
agent-browser errors
agent-browser network requests
agent-browser eval "document.title"

# State and tabs
agent-browser cookies get
agent-browser storage local get
agent-browser tab new
agent-browser tab list
agent-browser tab 2
agent-browser close
```

## Working Rules

- Prefer `wait --load networkidle` after navigation-heavy steps.
- Prefer `snapshot -i` before `click`, `fill`, or `select` when the page is not stable enough for CSS selectors.
- Use `console`, `errors`, and `network requests` before concluding that a page is broken.
- Use `--profile <path>` when a persistent login or browser profile matters.
- Use `--session <name>` when separate browser contexts are required in the same task.
- If `agent-browser` is missing, tell the user exactly how to install it before continuing.
"""

FORBIDDEN_TEXT = [
    "cl" + "aude",
    ".cl" + "aude",
    "Ask" + "UserQuestion",
]

COMMON_REPLACEMENTS = [
    ("~/.claude/", "~/.codex/"),
    ("`/", "`"),
    ("CLAUDE.md", "AGENTS.md"),
    ("TODOS.md", "TODO.md"),
    ("TODOS.md updates", "TODO.md updates"),
    ("Do not read AGENTS.md or other docs", "Do not read repo docs or other docs"),
    ("Do not read CLAUDE.md or other docs", "Do not read repo docs or other docs"),
    ("use Ask" "UserQuestion to", "ask the user directly to"),
    ("using Ask" "UserQuestion to", "asking the user directly to"),
    ("use a separate Ask" "UserQuestion with", "ask the user directly in a separate message with"),
    ("use a separate Ask" "UserQuestion", "ask the user directly in a separate message"),
    ("call Ask" "UserQuestion individually", "ask the user directly, one issue at a time"),
    ("call Ask" "UserQuestion", "ask the user directly"),
    ("One Ask" "UserQuestion round at the end", "one direct question round at the end"),
    ("Ask" "UserQuestion once per issue", "ask the user directly once per issue"),
    ("Ask" "UserQuestion individually", "ask the user directly"),
    ("Every Ask" "UserQuestion MUST", "Every direct user question must"),
    ("Ask" "UserQuestion format", "Question format"),
    ("One issue = one Ask" "UserQuestion call.", "One issue = one direct user question."),
    ("If any Ask" "UserQuestion goes unanswered", "If any direct user question goes unanswered"),
    ("If the user does not respond to an Ask" "UserQuestion", "If the user does not respond to a direct user question"),
    ("When using Ask" "UserQuestion", "When asking the user directly"),
    ("Cl" "aude Code", "Codex"),
    ("Cl" "aude.ai", "the current agent UI"),
    ("Cl" "aude", "Codex"),
]

SKILL_SPECIFIC_REPLACEMENTS = {
    "plan-ceo-review": [
        ("Then read AGENTS.md, TODO.md, and any existing architecture docs. Map:", "Then read `AGENTS.md`, `TODO.md`, `TODOS.md`, and any existing architecture docs. Map:"),
        ('For LLM/prompt changes: Check AGENTS.md for the "Prompt/LLM changes" file patterns.', 'For LLM/prompt changes: check `AGENTS.md` or nearby repo instructions for the prompt/eval file patterns.'),
        ("Then present options: **A)** Add to TODO.md as a vision item", "Then present options: **A)** Add to `TODO.md` as a vision item"),
        ("Then present options: **A)** Add to TODO.md", "Then present options: **A)** Add to `TODO.md`"),
        ("TODO.md or it doesn't exist.", "`TODO.md` or `TODOS.md`; otherwise note the gap explicitly."),
    ],
    "plan-eng-review": [
        ('For LLM/prompt changes: check the "Prompt/LLM changes" file patterns listed in AGENTS.md.', 'For LLM/prompt changes: check `AGENTS.md` or nearby repo instructions for the prompt/eval file patterns.'),
        ("Then present options: **A)** Add to TODO.md", "Then present options: **A)** Add to `TODO.md`"),
    ],
    "review": [
        ("Read `." "cl" "aude/skills/review/checklist.md`.", "Read `references/checklist.md`."),
        ("If CRITICAL issues found: output all findings, then for EACH critical issue use a separate Ask" "UserQuestion with the problem, your recommended fix, and options (A: Fix it now, B: Acknowledge, C: False positive — skip).", "If critical issues are found: output all findings, then ask the user directly about each critical issue with the problem, your recommended fix, and options (A: Fix it now, B: Acknowledge, C: False positive — skip)."),
    ],
    "ship": [
        ("Match against these patterns (from AGENTS.md):", "Match against these patterns (from `AGENTS.md` or nearby repo instructions):"),
        ("Read `." "cl" "aude/skills/review/checklist.md`.", "Read `references/review-checklist.md`."),
        ("use a separate Ask" "UserQuestion with:", "ask the user directly, one issue at a time, with:"),
        ("🤖 Generated with [Codex Code](https://cl" "aude.com/cl" "aude-code)\n", ""),
    ],
    "retro": [
        ("Designed for a senior IC/CTO-level builder using Codex as a force multiplier.", "Designed for a senior IC/CTO-level builder using a coding agent as a force multiplier."),
        ("When the user types `retro`, run this skill.", "Use this skill when the user asks for a retrospective or invokes `retro`."),
    ],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", required=True)
    parser.add_argument("--dest-dir", required=True)
    return parser.parse_args()


def read_frontmatter_and_body(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text()
    match = re.match(r"^---\n.*?\n---\n(.*)$", text, re.S)
    if not match:
        raise ValueError(f"missing frontmatter in {path}")
    frontmatter_text = text.split("---", 2)[1]
    return parse_frontmatter(frontmatter_text), match.group(1).lstrip("\n")


def format_frontmatter_description(description: str) -> str:
    body = description.rstrip("\n").splitlines()
    if not body:
        return "description: \n"

    return "description: |\n" + "\n".join(f"  {line}" for line in body) + "\n"


def parse_frontmatter(frontmatter: str) -> dict[str, str]:
    meta: dict[str, str] = {}
    lines = [line.rstrip("\n") for line in frontmatter.splitlines()]
    i = 0
    while i < len(lines):
        line = lines[i]
        if ":" not in line:
            i += 1
            continue

        key, value = line.split(":", 1)
        key = key.strip()
        value = value.lstrip()

        if value in {"|", "|-", "|+", ""}:
            i += 1
            block: list[str] = []
            while i < len(lines) and lines[i].startswith("  "):
                block.append(lines[i][2:])
                i += 1
            meta[key] = "\n".join(block).rstrip()
            continue

        meta[key] = value
        i += 1

    return meta


def discover_skills(source_dir: Path) -> list[str]:
    discovered = []
    for entry in sorted(source_dir.iterdir()):
        if not entry.is_dir():
            continue
        if not (entry / "SKILL.md").exists():
            continue
        discovered.append(entry.name)
    return discovered


def copy_supporting_files(source_skill_dir: Path, dest_skill_dir: Path) -> None:
    for item in source_skill_dir.iterdir():
        if item.name == "SKILL.md":
            continue
        target = dest_skill_dir / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, target)


def apply_replacements(text: str, replacements: list[tuple[str, str]]) -> str:
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def clean_generic_body(skill: str, body: str) -> str:
    body = body.replace("\r\n", "\n")
    body = apply_replacements(body, COMMON_REPLACEMENTS)
    body = apply_replacements(body, SKILL_SPECIFIC_REPLACEMENTS.get(skill, []))
    body = body.replace("Ask" "UserQuestion", "direct user question")
    body = re.sub(r"(?m)^allowed-tools:\n(?:  - .*\n)+", "", body)
    body = re.sub(r"(?m)^🤖 Generated with .*\n?", "", body)
    body = re.sub(r"(?m)^Use when the user types `[^`]+`, run this skill\.\n", "", body)
    body = body.replace("AGENTS.md for the \"Prompt/LLM changes\" file patterns", "`AGENTS.md` for the prompt/eval file patterns")
    body = body.replace("direct user question format", "Question format")
    body = body.replace("one direct user question round at the end", "one direct question round at the end")
    body = body.replace("direct user question call", "direct user question")
    body = body.replace("using direct user question to", "asking the user directly to")
    body = body.replace("use direct user question to", "ask the user directly to")
    body = body.replace("Present each potential TODO as its own individual direct user question.", "Present each potential TODO as its own individual direct user question.")
    body = body.replace("TODO.md updates", "`TODO.md` updates")
    body = body.replace("Add to TODO.md", "Add to `TODO.md`")
    body = body.replace("TODO.md or it doesn't exist", "`TODO.md` or it doesn't exist")
    body = body.replace("TODO.md updates:", "`TODO.md` updates:")
    body = body.replace("TODO.md updates     |", "`TODO.md` updates     |")
    body = body.replace("TODO.md updates: ___", "`TODO.md` updates: ___")
    body = body.replace("TODO.md as a vision item", "`TODO.md` as a vision item")
    body = re.sub(r"(?m)^-{3,}\n", "---\n", body)
    body = re.sub(r"\n{3,}", "\n\n", body).strip() + "\n"
    return GENERATOR_NOTE + UNIVERSAL_RUNTIME_NOTES + body


def validate_no_forbidden_text(path: Path) -> None:
    text = path.read_text().lower()
    for forbidden in FORBIDDEN_TEXT:
        if forbidden.lower() in text:
            raise ValueError(f"forbidden text {forbidden!r} found in {path}")


def write_skill(dest_dir: Path, skill: str, body: str, description: str | None = None) -> None:
    target_dir = dest_dir / "skills" / skill
    target_dir.mkdir(parents=True, exist_ok=True)
    skill_description = description or f"Use the {skill} skill."
    description_text = format_frontmatter_description(skill_description)
    skill_text = (
        "---\n"
        f"name: {skill}\n"
        f"{description_text}"
        "---\n\n"
        f"{body}"
    )
    (target_dir / "SKILL.md").write_text(skill_text)
    validate_no_forbidden_text(target_dir / "SKILL.md")


def copy_references(source_dir: Path, dest_dir: Path) -> None:
    review_ref = dest_dir / "skills" / "review" / "references"
    review_ref.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source_dir / "review" / "checklist.md", review_ref / "checklist.md")

    ship_ref = dest_dir / "skills" / "ship" / "references"
    ship_ref.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source_dir / "review" / "checklist.md", ship_ref / "review-checklist.md")


def clear_generated_skills(dest_dir: Path) -> None:
    skills_dir = dest_dir / "skills"
    if skills_dir.exists():
        shutil.rmtree(skills_dir)
    skills_dir.mkdir(parents=True, exist_ok=True)


def main() -> None:
    args = parse_args()
    source_dir = Path(args.source_dir).resolve()
    dest_dir = Path(args.dest_dir).resolve()

    clear_generated_skills(dest_dir)
    copy_references(source_dir, dest_dir)

    for skill in discover_skills(source_dir):
        if skill == "browse":
            write_skill(
                dest_dir,
                skill,
                BROWSE_SKILL,
                description=SKILL_OVERRIDES["browse"]["description"],
            )
            continue

        frontmatter, body = read_frontmatter_and_body(source_dir / skill / "SKILL.md")
        write_skill(
            dest_dir,
            skill,
            clean_generic_body(skill, body),
            description=frontmatter.get("description"),
        )
        copy_supporting_files(source_dir / skill, dest_dir / "skills" / skill)


if __name__ == "__main__":
    main()
